# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HDA Checkin

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 10 0 * * *
    # 国家时间 0点 北京时间8点触发

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Install pipfile
        run: |
          pipenv install
      - name: pipenv shell
        run: |
          pipenv run python run.py hda signin
        env:
          CONFIG: ${{ secrets.HDA_CONFIG }}
